ignore:
  - "m3rdparty"
  - "cmake"
  - "scripts"
  - "include/mutils/tinydir"
  - "include/mutils/tclap"
  - "include/mutils/stb"
  - "include/mutils/mpc"
  - "include/mutils/kiss_fft"
  - "include/mutils/dr_libs"
  - "include/mutils/cpptoml"
  - "include/mutils/tracy"
  - "src/fmt"
  - "src/kiss_fft"
  - "src/mpc"
  - "src/tracy"
