environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      VCVARS_FILE: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
      VCVARS_ARG: x86
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      VCVARS_FILE: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
      VCVARS_ARG: x86_amd64
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      VCVARS_FILE: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat
      VCVARS_ARG:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      VCVARS_FILE: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat
      VCVARS_ARG:

install:
  - call "%VCVARS_FILE%" %VCVARS_ARG%

build_script:
  - mkdir build
  - cd build
  - cmake .. -G "NMake Makefiles"
  - nmake
  - ctest --output-on-failure
