version: "{branch} #{build}"

image:
  - Visual Studio 2017
  - Visual Studio 2019

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

build:
  parallel: true

before_build:
  - if exist build RMDIR /S /Q build
  - if not exist build mkdir build
  - cd build
  - cmake -A %PLATFORM% ..

build_script:
  - cmake --build . --config %CONFIGURATION%

test_script:
  - ctest --output-on-failure -C %CONFIGURATION%
