name: Coverage

on: [push]
jobs:
  build:
    name: "coverage-ubuntu"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: actions/checkout@master
    
    - name: Python install
      run: |
        python -m pip install --upgrade pip
        python -m pip install wheel
        python -m pip install git+git://github.com/eddyxu/cpp-coveralls.git
        
    - name: Install GL
      run: |
        sudo apt-get install freeglut3-dev

        
    - name: Prebuild Linux
      working-directory: ${{github.workspace}}
      run: |
        ./prebuild.sh
    
      #- name: Setup tmate session
      # uses: mxschmitt/action-tmate@v3
        
    - name: Coverage
      working-directory: ${{github.workspace}}
      run: |
        mkdir build
        cd build
        cmake -DENABLE_COVERAGE=ON -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER="g++" ..
        make
        ./unittests
        bash <(curl -s https://codecov.io/bash)
    
    - name: Coverage-Report-Gen
      run: |
        find .. -name *.gcno | xargs gcov
        lcov -c -d .. -o coverage.info
        lcov --remove coverage.info 'm3rdparty' 'cmake' 'scripts' -o coverage.info
        genhtml coverage.info
                
    - name: codacy-coverage-reporter
      uses: codacy/codacy-coverage-reporter-action@master
      with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage.info

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      
        
